"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cutedots.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'includes': ['h5py.defs', 'h5py.utils', 'h5py._proxy', 'h5py.h5ac'],
    'iconfile': 'icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
